#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook "ntp",
	"1.6.4"
cookbook "openssh",
	"1.3.4"
cookbook "php",
	"1.4.6"
cookbook "apache2",
	"1.10.4"
cookbook "mysql",
	"5.3.6"
cookbook "git",
	"4.0.2"
cookbook "apt",
	"2.4.0"
cookbook "composer",
    :git => "git://github.com/Morphodo/composer.git"
cookbook "typo3_flow",
    :git => "git://github.com/Morphodo/typo3_flow-chef-recipe.git"

