maintainer       "Thomas Layh"
maintainer_email "thomas@layh.com"
license          "MIT"
description      "Install and configure TYPO3 Neos"
version          "0.0.1"

depends			"ntp"
depends			"openssh"
depends			"php"
depends			"apache2"
depends			"mysql"
depends			"git"
depends			"apt"
depends			"composer"
depends			"typo3_flow"
